// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Barb.Repl")>]
[<assembly: AssemblyProductAttribute("Barb")>]
[<assembly: AssemblyDescriptionAttribute("A Simple Dynamic Scripting Language for .NET")>]
[<assembly: AssemblyVersionAttribute("1.0.5")>]
[<assembly: AssemblyFileVersionAttribute("1.0.5")>]
[<assembly: InternalsVisibleToAttribute("Barb.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Barb.Repl"
    let [<Literal>] AssemblyProduct = "Barb"
    let [<Literal>] AssemblyDescription = "A Simple Dynamic Scripting Language for .NET"
    let [<Literal>] AssemblyVersion = "1.0.5"
    let [<Literal>] AssemblyFileVersion = "1.0.5"
    let [<Literal>] InternalsVisibleTo = "Barb.Tests"
